name: main-pipeline

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: echo "CI OK"

  release-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build images
        run: echo "Images OK"

  deploy:
    runs-on: ubuntu-latest
    needs:
      - ci
      - release-images
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        run: echo "Deploy après CI + release"